--DROP TABLE EQUIPAMENTO;
--DROP TABLE SOLICITANTE;
--DROP TABLE AGENDA;

INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Laser', 'Para apontar para a tela', '0');
INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Data Show', 'Projetor Hitachi, branco, HD', '0');
INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Notebook', 'Notebook Acer', '0');
INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Caixa de som', 'Caixa de 50 watts para uso no auditorio', '0');
INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Microfone', 'Microfone sem fio  para uso no auditorio', '0');
INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Scanner', 'Scanner HP portatil', '0');
INSERT INTO EQUIPAMENTO (NOME, DESCRICAO, STATUS) VALUES('Notebook', 'Notebook Samsung', '0');